cmake_minimum_required(VERSION 3.13)

project(jsoncpp_vendor)

find_package(ament_cmake REQUIRED)

include(ExternalProject)

set(JSONCPP_VERSION 1.9.5)
set(JSONCPP_INSTALL_DIR ${CMAKE_CURRENT_BINARY_DIR}/jsoncpp_install)

ExternalProject_Add(jsoncpp
  GIT_REPOSITORY https://github.com/open-source-parsers/jsoncpp
  GIT_TAG ${JSONCPP_VERSION}
  UPDATE_COMMAND ""
  CMAKE_ARGS
    -DCMAKE_INSTALL_PREFIX=${JSONCPP_INSTALL_DIR}
    -DJSONCPP_WITH_TESTS=OFF
    -DJSONCPP_WITH_POST_BUILD_UNITTEST=OFF
    -DJSONCPP_WITH_STRIP=OFF
    -DBUILD_SHARED_LIBS=ON
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
)

add_custom_target(${PROJECT_NAME} ALL DEPENDS jsoncpp)

install(
  DIRECTORY ${JSONCPP_INSTALL_DIR}/
  DESTINATION .
  USE_SOURCE_PERMISSIONS
)

ament_package()
