<?xml version="1.0"?>
<package format="3">
  <name>jsoncpp_vendor</name>
  <version>0.1.0</version>
  <description>Vendor package to provide JsonCpp from source for easy_perception_deployment.</description>
  <maintainer email="beyhy94@gmail.com">rosi</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
