bool trigger   # EMD sets true to request EPD to run one perception cycle
---
bool success   # indicate if EPD pipeline has successfully completed
bool tracking_enabled   # Whether or not grasp planner should use EPDObjectLocalization or EPDObjectTracking. 
EPDObjectLocalization epd_localization # informational, e.g. for error messages.
EPDObjectTracking epd_tracking # informational, e.g. for error messages.
